services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dialisis_user
      POSTGRES_PASSWORD: dialisis_pass
      POSTGRES_DB: centro_dialisis
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
